name: brfss_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn=1.6.1
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - nbconvert
  - pip
  - pip:
      - imbalanced-learn==0.13.0
      - xgboost
